version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      kafkademo:
        ipv4_address: 172.20.0.254
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.0.254
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      kafkademo:
        ipv4_address: 172.20.0.101

networks:
  kafkademo:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
